channels:
  - rapidsai-nightly
  - rapidsai
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python[version='>=3.10,<3.14']
  - c-compiler
  - certifi
  - cmake[version='>=3.30.4']
  - cuda-cudart-dev
  - cuda-nvcc
  - cuda-profiler-api
  - cuda-python[version='>=12.6.2,<13.0a0']
  - cuda-version=12.9
  - cudf==25.10.00
  - cupy[version='>=12.0.0']
  - cuvs==25.10.00
  - cxx-compiler
  - cython[version='>=3.0.0']
  - dask-cuda==25.10.00
  - dask-cudf==25.10.00
  - dask-ml
  - doxygen=1.9.1
  - gcc_linux-64==14.3.0
  - graphviz
  - hdbscan[version='>=0.8.39,<0.8.40']
  - hypothesis[version='>=6.0,<7']
  - ipykernel
  - ipython
  - joblib[version='>=0.11']
  - libcublas-dev
  - libcufft-dev
  - libcumlprims==25.10.00
  - libcurand-dev
  - libcusolver-dev
  - libcusparse-dev
  - libcuvs==25.10.00
  - libraft==25.10.00
  - librmm==25.10.00
  - matplotlib-base
  - nbsphinx
  - ninja
  - nltk
  - numba[version='>=0.59.1,<0.62.0a0']
  - numpy[version='>=1.23,<3.0a0']
  - numpydoc[version='<1.9']
  - packaging
  - pydata-sphinx-theme!=0.14.2
  - pylibraft==25.10.00
  - pynndescent
  - pytest-benchmark
  - pytest-cases
  - pytest-cov
  - pytest-xdist
  - pytest==8.4.2
  - pyyaml
  - raft-dask==25.10.00
  - rapids-build-backend==0.4.1
  - rapids-dask-dependency==25.10.00
  - rapids-logger[version='0.1.*,>=0.0.0a0']
  - recommonmark
  - rmm==25.10.00
  - scikit-build-core[version='>=0.10.0']
  - scikit-learn[version='>=1.4']
  - scipy[version='>=1.8.0']
  - seaborn
  - sphinx-copybutton
  - sphinx-markdown-tables
  - sphinx==8.2.3
  - statsmodels
  - sysroot_linux-64==2.28
  - tenacity
  - treelite==4.4.1
  - umap-learn==0.5.7
  - xgboost[version='>=2.1.0']
  - ccache
  - pre-commit
  - rich
